platform :ios, '8.0'
target 'XYBKDemo' do
pod 'MBProgressHUD', '~> 1.1.0'
pod 'MJRefresh', '~> 3.1.15.3'
pod 'AFNetworking', '~> 3.2.0'
pod 'SDWebImage', '~> 4.3.3'
pod 'IQKeyboardManager', '~> 6.0.2'
pod 'Masonry', '~> 1.1.0'
pod 'BaiduMapKit'

end
